INSERT INTO system_configs (group_name, key, value, remark, updated_at) VALUES
('site', 'app_name', '喵搭', '应用名称', NOW()),
('site', 'logo_url', '/logo.png', '用户端 Logo 地址', NOW()),
('site', 'about_slogan', '您身边的陪伴服务平台', '关于页标语', NOW()),
('site', 'about_version', 'v1.0.0', '版本号', NOW()),
('site', 'about_build', 'Build 20250625', '构建号', NOW()),
('site', 'about_team', '喵搭科技', '开发团队', NOW()),
('site', 'about_website', 'www.miaoda.com', '官方网站', NOW()),
('site', 'about_service_phone', '400-888-0000', '关于页客服热线', NOW()),
('site', 'about_service_email', 'support@miaoda.com', '关于页联系邮箱', NOW()),
('site', 'about_intro', '喵搭专注于本地生活陪伴服务，连接用户与经过认证的达人，提供休闲、娱乐、按摩、影院等多场景服务。', '关于页介绍', NOW()),
('site', 'about_copyright', '© 2025 喵搭科技 版权所有', '版权信息', NOW()),
('site', 'about_license', '增值电信业务经营许可证: 川B2-2025XXXX', '许可证信息', NOW()),
('site', 'about_icp', 'ICP备案号: 川ICP备2025XXXXXXXX号', 'ICP备案号', NOW()),
('site', 'support_title', '在线客服', '客服页标题', NOW()),
('site', 'support_subtitle', '喵搭官方客服', '客服名称', NOW()),
('site', 'support_desc', '咨询订单、退款、预约和平台规则等问题', '客服页说明', NOW()),
('site', 'support_welcome', '您好！喵搭客服为您服务，请问有什么可以帮您的？', '客服欢迎语', NOW()),
('site', 'support_auto_reply', '收到您的消息啦！我们的客服正在处理中，稍后会有专人回复您~', '客服自动回复', NOW()),
('site', 'support_quick', '如何下单？,退款政策,优惠券使用,投诉建议', '快捷问题，英文逗号分隔', NOW()),
('site', 'support_phone', '400-888-0000', '客服热线', NOW()),
('site', 'support_email', 'support@miaoda.com', '客服邮箱', NOW()),
('site', 'support_work_time', '09:00 - 22:00', '服务时间', NOW()),
('site', 'support_notice', '紧急订单问题建议直接拨打客服热线，普通咨询可在线留言。', '客服提示文案', NOW())
ON CONFLICT (group_name, key) DO NOTHING;
